VoiceManagementSystem/TVMS/TVMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.HomePage.as_view(), name = 'home'),
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url('^test/$', views.TestPage.as_view(), name = 'test'),
    url('^thanks/$', views.ThanksPage.as_view(), name = 'thanks'),
    ### Patterns for User Based content
    url('^Voiceapp/', include('Voiceapp.urls', namespace='Voiceapp')),
    url('^api/users/', include('accounts.api.urls', namespace='users-api')),

    url('^api/voiceapp/', include('Voiceapp.api.urls', namespace='voiceapp-api')),

]

VoiceManagementSystem/TVMS/Voiceapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'Voiceapp'

urlpatterns = [
    ## url pattern for admin view
    url(r'myteams/$', views.team_list, name='my_teams'),
    url(r'myteams/(?P<pk>\d+)$', views.team_details, name='team_candidate'),
    ## search functionality for admin
    url(r'results/$', views.search, name= 'search'),

    ## url pattern for candidate view
    url(r'mycandidates/$', views.CandidateswithMentorListView.as_view(), name='my_candidates'),
    url(r'mycandidates/(?P<pk>\d+)$', views.activity_list, name='my_activities'),

]

VoiceManagementSystem/TVMS/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_view
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$', auth_view.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    url(r'logout/$', auth_view.LogoutView.as_view(), name='logout'),
]

VoiceManagementSystem/TVMS/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>The Voice</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'CSS/master.css'%}">
</head>
<body>
<nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">


            <a class="navbar-brand mynav" href="{% url 'home' %}">The Voice</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                                <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple">Log out</a></li>
    						{% else %}
                                <!--<li><a href=""class="btn btn-simple">Groups</a></li>-->
                                <li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Log in</a></li>

    						{% endif %}
    					</ul>



    			</div>
    		</nav>
<div class = "container mycontent">
{% block content %}
{% endblock %}
</div>

</body>
</html>

VoiceManagementSystem/TVMS/templates/index.html
{%extends "base.html"%}

{% block content %}
<h1> Welcome to TV show</h1>
{% endblock %}

VoiceManagementSystem/TVMS/templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  {% if user.is_superuser %}

    <h1>Welcome Admin</h1>
    <h2><a href="{% url 'Voiceapp:my_teams'%}"> Teams</a></h2>


  {%else%}
    <h1>Welcome {{request.user.username}} !!! </h1>
    <h2><a href="{% url 'Voiceapp:my_candidates'%}"> Candidates</a></h2>


  {%endif%}

</div>

{% endblock %}

VoiceManagementSystem/TVMS/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h2>Thanks for visiting!</h2>
{% endblock %}