VoiceManagementSystem/TVMS/TVMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('^$', views.HomePage.as_view(), name = 'home'),
    url('^accounts/', include('accounts.urls', namespace='accounts')),
    url('^accounts/', include('django.contrib.auth.urls')),
    url('^test/$', views.TestPage.as_view(), name = 'test'),
    url('^thanks/$', views.ThanksPage.as_view(), name = 'thanks'),
    ### Patterns for User Based content
    url('^Voiceapp/', include('Voiceapp.urls', namespace='Voiceapp')),
    url('^api/users/', include('accounts.api.urls', namespace='users-api')),

    url('^api/voiceapp/', include('Voiceapp.api.urls', namespace='voiceapp-api')),

]

VoiceManagementSystem/TVMS/Voiceapp/api/urls.py
from django.conf.urls import url
from . import views

app_name = 'Voiceapp'

urlpatterns = [
    # ## url pattern for admin view
     url(r'myteams/$', views.TeamListAPIView.as_view(), name='my_teams'),
     url(r'myteams/(?P<pk>\d+)$', views.TeamDetailsAPIView.as_view(), name='team_candidate'),

    # ## search functionality for admin
    # url(r'results/$', views.search, name= 'search'),
    #
    # ## url pattern for candidate view
     url(r'mycandidates/$',views.CandidateListAPIView.as_view(), name='my_candidates'),
    # url(r'mycandidates/(?P<pk>\d+)$', views.activity_list, name='my_activities'),

]

VoiceManagementSystem/TVMS/Voiceapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'Voiceapp'

urlpatterns = [
    ## url pattern for admin view
    url(r'myteams/$', views.team_list, name='my_teams'),
    url(r'myteams/(?P<pk>\d+)$', views.team_details, name='team_candidate'),
    ## search functionality for admin
    url(r'results/$', views.search, name= 'search'),

    ## url pattern for candidate view
    url(r'mycandidates/$', views.CandidateswithMentorListView.as_view(), name='my_candidates'),
    url(r'mycandidates/(?P<pk>\d+)$', views.activity_list, name='my_activities'),

]

VoiceManagementSystem/TVMS/Voiceapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.db.models import Avg
from statistics import mean
# Create your models here.

class Team(models.Model):
    team_name = models.CharField(max_length=256)
    mentor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.team_name

class Candidate(models.Model):
    candidate_name = models.CharField(max_length=256)
    team = models.ForeignKey(Team, related_name='Teams', on_delete=models.SET_NULL, null=True)

    # Calculate average score for candidate
    def get_avg_score(self):
        average=Activity.objects.filter(candidate=self).aggregate(average_rating = Avg('activityscore_by_mentor__score'))
        return average['average_rating']

    def __str__(self):
        return self.candidate_name

    def __unicode__(self):
        return '%s' % (self.candidate_name)


class Activity(models.Model):
    song_name = models.CharField(max_length=256)
    Date_of_performance = models.DateField()
    candidate = models.ForeignKey(Candidate, related_name='Candidates', on_delete=models.CASCADE)

    # Calculate average score for activity
    def activity_avg_score(self):
        average =  list(self.activityscore_by_mentor_set.aggregate(Avg('score')).values())[0]
        return average

    def __str__(self):
        return " {} - {} - {}".format(self.song_name, self.Date_of_performance, self.candidate)


class ActivityScore_by_mentor(models.Model):
    activity = models.ForeignKey(Activity, related_name='Scores',on_delete=models.CASCADE)
    mentor = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    def __str__(self):
        return "ACtivity : {}, score : {}, mentor: {}".format(self.activity, self.score, self.mentor)

VoiceManagementSystem/TVMS/Voiceapp/api/views.py
from rest_framework.generics import ListAPIView, RetrieveAPIView
from ..models import Candidate, Team, Activity
from .serializers import CandidateListSerializer, CandidateDetailSerializer, TeamListSerializer, TeamDetailSerializer,ActivityListSerializer
from django.db.models import Avg, Q
from rest_framework.response import Response
### rest frameworks build in filters
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from rest_framework.authentication import TokenAuthentication

class ActivityListAPIView(ListAPIView):
    queryset = Activity.objects.all().annotate(average_score=Avg('Scores__score'))
    permission_classes = [IsAuthenticated]
    serializer_class = ActivityListSerializer

    # def get_queryset(self):
    #     queryset = Activity.objects.all().annotate(average_score=Avg('Scores__score'))
    #     print(queryset)
    #     return queryset


class CandidateListAPIView(ListAPIView):
    permission_classes = [IsAuthenticated]
    queryset = Candidate.objects.all()
    serializer_class = CandidateListSerializer

class CandidateDetailsView(RetrieveAPIView):
    permission_classes = [IsAuthenticated]
    queryset = Candidate.objects.all()
    serializer_class = CandidateDetailSerializer

class TeamListAPIView(ListAPIView):
    serializer_class = TeamListSerializer
    permission_classes = [IsAdminUser, IsAuthenticated]

    def get_queryset(self):
        query = self.request.GET.get('q')
        if (query):
            teams_activity_score = Team.objects.filter(Q(team_name__icontains=query)).annotate(
            average_score=Avg('Teams__Candidates__Scores__score'))
        else:
            teams_activity_score = Team.objects.all().annotate(average_score=Avg('Teams__Candidates__Scores__score'))

        return teams_activity_score


class TeamDetailsAPIView(RetrieveAPIView):
    queryset = Team.objects.all()

    permission_classes = [IsAdminUser, IsAuthenticated]
    lookup_field = 'pk'
    serializer_class = TeamDetailSerializer

VoiceManagementSystem/TVMS/Voiceapp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Count, Prefetch, Q
#from django.views.generic.list_detail import object_list
from . import models

# admin view. list of all teams
@login_required()
def team_list(request):
    # All teams objects with annotation to get average team score
    teams_activity_score = models.Team.objects.all().annotate(average_score = Avg('Teams__Candidates__Scores__score'))
    template = 'Voiceapp/team_list.html'
    #template = 'Voiceapp/team_list_for_admin.html'

    context = {
        'score' : teams_activity_score
    }
    return render(request, template, context)

### Search functionality for admin. filter team by team name
@login_required()
def search(request):
    #template = 'Voiceapp/team_list_for_admin.html'
    template = 'Voiceapp/team_list.html'

    query = request.GET.get('q')
    if(query):
        teams_activity_score = models.Team.objects.filter(Q(team_name__icontains=query)).annotate(average_score = Avg('Teams__Candidates__Scores__score'))
    else:
        teams_activity_score = models.Team.objects.all().annotate(average_score=Avg('Teams__Candidates__Scores__score'))

    context = {
        'score' : teams_activity_score
    }
    return render(request, template, context)


## activity details of candidates for the team
@login_required()
def team_details(request,pk):

    team = models.Team.objects.get(pk=pk)
    candidate_activities=models.Activity.objects.select_related('candidate__team').filter(candidate__team=team)

    #template = 'Voiceapp/candidate_activity_list_per_team.html'
    template = 'Voiceapp/candidate_activity_list_per_team.html'

    context = {
        'team' : team,
        'candidate_activities' : candidate_activities
    }
    return render(request, template, context)


## lists the candidate for mentor template
class CandidateswithMentorListView(LoginRequiredMixin, ListView):
    model = models.Team
    template_name = 'Voiceapp/candidate_list_mentored_by_user.html'
    def get_queryset(self):
        result =models.Candidate.objects.select_related('team').filter(team__mentor=self.request.user)
        return result


# @login_required
def activity_list(request, pk):
    candidate = models.Candidate.objects.get(pk=pk)
    activities = models.Activity.objects.annotate(average_score=Avg('Scores__score')).filter(candidate = candidate)
    final_avearge_score = activities.aggregate(Avg('average_score'))

    candidate_activity_score = models.Candidate.objects.all().annotate(average_score=Avg('Candidates__Scores__score')) ## working correct

    template = 'Voiceapp/candidate_activity_details.html'
    context = {
        'candidate' : candidate,
        'activities': activities,
        'activity_score': candidate_activity_score,
        'final_score' : final_avearge_score['average_score__avg']
    }
    return render(request, template, context)

VoiceManagementSystem/TVMS/Voiceapp/templates/Voiceapp/candidate_activity_details.html
{% extends "base.html" %}

{% block content %}
    <h1>Activity Details for : {{candidate.candidate_name}}</h1>

    <table>
      <tr>
        <th>Song Name</th>
        <th>Date of Performance</th>
        <th>Average Score</th>
      </tr>
        {%for act in activities%}
        <tr>
            <td>{{act.song_name}}</td>
            <td>{{act.Date_of_performance}}</td>
            <td>{{act.average_score|floatformat:2}}</td>

        </tr>
        {%endfor%}

    </table>

<h2> Candidate's average score : {{final_score|floatformat:2}}</h2>
{% endblock %}

VoiceManagementSystem/TVMS/Voiceapp/templates/Voiceapp/candidate_activity_list_per_team.html
{% extends "base.html" %}

{% block content %}
<h1> Team = {{team.team_name}}</h1>
    {%if candidate_activities%}
        <h2>Activity Details here</h2>

        <table>
            <tr>
                <th>Song Name</th>
                <th>Date of Performance</th>
                <th>Candidate Name</th>
            </tr>
            {% for can in candidate_activities %}
            <tr>
                <td>{{can.song_name}}</td>
                <td>{{can.Date_of_performance}}</td>
                <td>{{can.candidate.candidate_name}}</td>
            </tr>
            {%endfor%}


        </table>
    {%else%}
        <p> No Activity by candiadtes</p>
    {%endif%}

{% endblock %}

VoiceManagementSystem/TVMS/Voiceapp/templates/Voiceapp/candidate_list_mentored_by_user.html
{% extends "base.html" %}

{% block content %}
    <h1>Candidates</h1>


    {% if object_list %}

        <table>
            <tr>
            <th>Candiadte</th>
            <th>Team</th>

            </tr>

        {% for inst in object_list %}
            <tr>
            <th><a href="{%url 'Voiceapp:my_activities' inst.id%}">{{inst.candidate_name}} </a></th>
            <th>{{inst.team}}</th>

            </tr>


        {% endfor %}
        </table>



    {% else %}
      <p>There are no Candidates mentored.</p>
    {% endif %}       
{% endblock %}

VoiceManagementSystem/TVMS/Voiceapp/templates/Voiceapp/team_list.html
{% extends "base.html" %}

{% block content %}
<form method = 'GET' action="{%url 'Voiceapp:search' %}">
    <input name="q" value="{{request.GET.q}}" placeholder="Search here...">
    <button class="btn btn_sucess" type="submit"> Search
    </button>

</form>
    <h1>Teams Details:</h1>
    {%if score %}
        <table>
            <tr>
            <th>Team</th>
            <th>Team Average Score</th>

            </tr>
        {%for s in score %}
            <tr>
            <th><a href="{% url 'Voiceapp:team_candidate' s.id %}">{{s.team_name}}</a></th>
            <th>Average Score={{s.average_score|floatformat:2}}</th>

            </tr>
        {%endfor%}

        </table>


    {% else %}
      <p>There are no Teams mentored.</p>
    {%endif%}

{% endblock %}